version: "3.0"
services:
  adweb:
    build: .
    ports:
      - "8093:8093"
    depends_on:
          - "addb"
  addb:
    build: ./mysql
    volumes:
          - /home/docker/SemanticSoftworks/ad-microservice-db:/var/lib/mysql
    ports:
      - "3309:3309"
