FROM mysql

EXPOSE 3309

# 4 now...
#ENV MYSQL_DATABASE toolbox-transation-db
ENV MYSQL_DATABASE db_mjukvaru_admicroservice
#ENV MYSQL_USER mysql
#ENV MYSQL_PASSWORD mysql
#ENV MYSQL_ALLOW_EMPTY_PASSWORD yes
ENV MYSQL_TCP_PORT 3309
ENV MYSQL_ROOT_PASSWORD my-secret-pw

#RUN
#ENTRYPOINT ["/bin/sh", "-c", "mysql"]
#CMD ["mysql"]
